### 1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [1]:
import numpy as np
def non_zero_checker(arr):
    if np.all(arr!= 0):
        return "Has no zero numbers"
    else:
        return "Has zero"

arr1= np.array([1,2,3,4])
arr2=np.array([5,6,0,9])

print("For array arr1:", non_zero_checker(arr1))
print("For array arr2:", non_zero_checker(arr2))


For array arr1: Has no zero numbers
For array arr2: Has zero


### 2. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [2]:
#1
import numpy as np
def non_zero_checker(arr):
    if np.all(arr > 0):
        return "Is non-zero"
    else:
        return "is zero"

arr1= np.array([1,2,3,4])
arr2=np.array([5,6,0,9])

print("For array arr1:", non_zero_checker(arr1))
print("For array arr2:", non_zero_checker(arr2))

# or

import numpy as np

def any_non_zero(arr):
    return np.any(arr != 0)

# Test the function
arr1 = np.array([0, 0, 0, 0, 0])
arr2 = np.array([0, 0, 1, 0, 0])

print("For array arr1:", any_non_zero(arr1))
print("For array arr2:", any_non_zero(arr2))


For array arr1: Is non-zero
For array arr2: is zero
For array arr1: False
For array arr2: True


### 3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given

In [3]:
def elementwise_comparison(arr1,arr2,tolerance=1e-8): #1 followed by 8 zeros)
    equal= np.equal(arr1,arr2)

    within_tolerance = np.isclose(arr1,arr2, atol =tolerance)

    return equal,within_tolerance

arr1 = np.array([1.0, 2.0, 3.0, 4.0])
arr2 = np.array([1.0, 2.0000001, 3.0, 4.0])

equal, within_tolerance = elementwise_comparison(arr1, arr2)
print("Element-wise comparison for equality:", equal)
print("Element-wise comparison within a tolerance:", within_tolerance)

Element-wise comparison for equality: [ True False  True  True]
Element-wise comparison within a tolerance: [ True  True  True  True]


### 4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [4]:
import numpy as np

# Create an array of 10 zeros with dtype=int
zeros_array = np.zeros(10, dtype=int)

# Create an array of 10 ones with dtype=int
ones_array = np.ones(10, dtype=int)

# Create an array of 10 fives with dtype=int by multiplying 5 with an array of 10 ones
fives_array = 5 * np.ones(10, dtype=int)

# Concatenate the arrays to form a single array
result_array = np.concatenate([zeros_array, ones_array, fives_array])

print("Array of 10 zeros:", zeros_array)
print("Array of 10 ones:", ones_array)
print("Array of 10 fives:", fives_array)
print("Concatenated array:", result_array)


Array of 10 zeros: [0 0 0 0 0 0 0 0 0 0]
Array of 10 ones: [1 1 1 1 1 1 1 1 1 1]
Array of 10 fives: [5 5 5 5 5 5 5 5 5 5]
Concatenated array: [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 5 5 5 5 5 5 5 5 5 5]


### 5. Write a NumPy program to create an array of the integers from 30 to70.

In [5]:
### 5. Write a NumPy program to create an array of the integers from 30 to70.
integers_array = np.arange(30, 71)
print(integers_array)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


### 6. Write a NumPy program to create a 3x3 identity matrix

In [6]:
identity_matrix=np.eye(3,dtype=int)
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### 7. Write a NumPy program to generate a random number between 0 and 1

In [7]:
random_number = np.random.rand()
print(random_number)

0.36528558852405935


### 8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [8]:
import numpy as np

# Generate an array of 15 random numbers from a standard normal distribution
random_numbers = np.random.randn(15)

print("Array of 15 random numbers from a standard normal distribution:")
print(random_numbers)


Array of 15 random numbers from a standard normal distribution:
[ 0.04126414  0.56085852 -1.61852581  1.48950539 -1.18508492 -0.11208119
 -0.00353329  1.12211045  0.07169765 -0.31721086 -2.41380149 -0.33717484
  0.87034297  2.62076469 -0.58522517]


### 9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [9]:
# Create a vector with values ranging from 15 to 55
vector = np.arange(15, 56)

# Print all values except the first and last
print("All values except the first and last:", vector[1:-1])


All values except the first and last: [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


### 10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [10]:
import numpy as np

# Create a vector of length 5 filled with arbitrary integers from 0 to 10
vector = np.random.randint(0, 11, size=5)

print("Vector of length 5 filled with arbitrary integers from 0 to 10:", vector)


Vector of length 5 filled with arbitrary integers from 0 to 10: [0 9 3 0 7]


### 11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [11]:
import numpy as np

# Create a 10x10 matrix filled with zeros
matrix = np.zeros((10, 10) ,dtype=int)
matrix[0]=1
matrix[0: , -1]=1
matrix[-1]=1
matrix[0: , 0] = 1
matrix

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### 12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,3, 4, 5.

In [12]:
import numpy as np

# Create a 5x5 zero matrix
matrix = np.zeros((5, 5), dtype=int)

# Set the elements on the main diagonal to 1, 2, 3, 4, 5
np.fill_diagonal(matrix, [1, 2, 3, 4, 5])

print("5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5:")
print(matrix)


5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


### 13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.


In [13]:
import numpy as np

# Create a 4x4 zero matrix
matrix = np.zeros((4, 4),dtype=int)

# Set the elements off the main diagonal to alternate between 0 and 1
for i in range(4):
    if i % 2 == 0:
        matrix[i, i+1] = 1
    else:
        matrix[i, i-1] = 1

print("4x4 matrix with 0 and 1 staggered, with zeros on the main diagonal:")
print(matrix)


4x4 matrix with 0 and 1 staggered, with zeros on the main diagonal:
[[0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]]


### 14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz for

In [14]:

import numpy as np

# Define two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

# Save the arrays into a single compressed file
np.savez_compressed('arrays_compressed.npz', array1=array1, array2=array2)


### 15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values.

In [15]:

import numpy as np

def extract_numbers(array, threshold):
    # Extract numbers less than the threshold
    less_than_threshold = array[array < threshold]

    # Extract numbers greater than the threshold
    greater_than_threshold = array[array > threshold]

    return less_than_threshold, greater_than_threshold

# Test the function
array = np.array([1, 5, 10, 15, 20])
threshold = 10
less_than_threshold, greater_than_threshold = extract_numbers(array, threshold)

print("Numbers less than", threshold, ":", less_than_threshold)
print("Numbers greater than", threshold, ":", greater_than_threshold)

Numbers less than 10 : [1 5]
Numbers greater than 10 : [15 20]


### 16. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [16]:
import numpy as np

def extract_numbers(array, threshold):
    # Extract numbers less than the threshold
    less_than_threshold = array[array < threshold]

    # Extract numbers greater than the threshold
    greater_than_threshold = array[array > threshold]

    return less_than_threshold, greater_than_threshold

# Test the function
array = np.array([1, 5, 10, 15, 20])
threshold = 10
less_than_threshold, greater_than_threshold = extract_numbers(array, threshold)

print("Numbers less than", threshold, ":", less_than_threshold)
print("Numbers greater than", threshold, ":", greater_than_threshold)


Numbers less than 10 : [1 5]
Numbers greater than 10 : [15 20]
